# GitHub Sponsors funding file
# This file allows users to sponsor the project
#
# To enable GitHub Sponsors, first enroll at: https://github.com/sponsors
# Then uncomment and add your username below:
# github: TRC-Crypto
#
# For custom funding links (e.g., Patreon, Ko-fi, etc.), add them here:
# custom: ['https://patreon.com/yourusername', 'https://ko-fi.com/yourusername']
custom: []
